/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package profile;

import connection.Connector;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import login.tempUser;

/**
 *
 * @author Sathira Guruge
 */
public class userProfile extends javax.swing.JFrame {

    /**
     * Creates new form userProfile
     */
    public userProfile() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        initialize();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userleft = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        title1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        UserInfo = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        emp_allow = new javax.swing.JTextField();
        emp_mname = new javax.swing.JTextField();
        emp_lname = new javax.swing.JTextField();
        emp_mobile = new javax.swing.JTextField();
        emp_nic = new javax.swing.JTextField();
        emp_dob = new javax.swing.JTextField();
        emp_std = new javax.swing.JTextField();
        emp_pos = new javax.swing.JTextField();
        emp_leaves = new javax.swing.JTextField();
        emp_dedu = new javax.swing.JTextField();
        emp_id = new javax.swing.JTextField();
        emp_epf = new javax.swing.JTextField();
        emp_etf = new javax.swing.JTextField();
        emp_sal = new javax.swing.JTextField();
        emp_fname = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        emp_gender = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        emp_mail = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        emp_addr = new javax.swing.JTextArea();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel26 = new javax.swing.JLabel();
        emp_netSal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userleft.setBackground(new java.awt.Color(51, 51, 255));
        userleft.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        userleft.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 66, -1, 132));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 28)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Toothpaste");
        userleft.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 300, -1));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user1.png"))); // NOI18N
        userleft.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 190, 130));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logof.png"))); // NOI18N
        userleft.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 300, 90));

        getContentPane().add(userleft, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 740));

        title1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        title1.setForeground(new java.awt.Color(255, 255, 255));
        title1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title1.setText("User Profile");
        getContentPane().add(title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 1070, 70));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("First Name");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 130, -1));

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Middle Name");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 130, -1));

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Last Name");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 130, -1));

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel10.setForeground(java.awt.Color.white);
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("NIC");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 100, 80, -1));

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel11.setForeground(java.awt.Color.white);
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Employee ID");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 140, -1));

        jLabel12.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel12.setForeground(java.awt.Color.white);
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Mobile Number");
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 390, 130, -1));

        jLabel13.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel13.setForeground(java.awt.Color.white);
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Gender");
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, 130, -1));

        jLabel14.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel14.setForeground(java.awt.Color.white);
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Total Salary");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 660, 160, -1));

        jLabel15.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel15.setForeground(java.awt.Color.white);
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("Date Of Birth");
        jLabel15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 150, 130, -1));

        jLabel16.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel16.setForeground(java.awt.Color.white);
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Position");
        jLabel16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 250, 130, -1));

        jLabel17.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel17.setForeground(java.awt.Color.white);
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("Start Date");
        jLabel17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 200, 130, -1));

        jLabel18.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel18.setForeground(java.awt.Color.white);
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("Address");
        jLabel18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, 130, -1));

        UserInfo.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        UserInfo.setForeground(java.awt.Color.white);
        UserInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UserInfo.setText("Employee Details");
        getContentPane().add(UserInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 200, -1));

        jLabel20.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel20.setForeground(java.awt.Color.white);
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setText("Allowance");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 490, 130, -1));

        jLabel21.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel21.setForeground(java.awt.Color.white);
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel21.setText("Deduction");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 540, 160, -1));

        jLabel22.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel22.setForeground(java.awt.Color.white);
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel22.setText("EPF");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 490, 160, -1));

        jLabel23.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel23.setForeground(java.awt.Color.white);
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel23.setText("Net Salary");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 590, 160, -1));

        jLabel24.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel24.setForeground(java.awt.Color.white);
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel24.setText("Leaves");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 590, 160, -1));

        emp_allow.setEditable(false);
        emp_allow.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.blue, 2));
        emp_allow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_allowActionPerformed(evt);
            }
        });
        getContentPane().add(emp_allow, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 480, 200, 30));

        emp_mname.setEditable(false);
        emp_mname.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.blue, 2));
        emp_mname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_mnameActionPerformed(evt);
            }
        });
        getContentPane().add(emp_mname, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 190, 190, 30));

        emp_lname.setEditable(false);
        emp_lname.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.blue, 2));
        emp_lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_lnameActionPerformed(evt);
            }
        });
        getContentPane().add(emp_lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 240, 190, 30));

        emp_mobile.setEditable(false);
        emp_mobile.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.blue, 2));
        emp_mobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_mobileActionPerformed(evt);
            }
        });
        getContentPane().add(emp_mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 380, 190, 30));

        emp_nic.setEditable(false);
        emp_nic.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.blue, 2));
        emp_nic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_nicActionPerformed(evt);
            }
        });
        getContentPane().add(emp_nic, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 90, 190, 30));

        emp_dob.setEditable(false);
        emp_dob.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.blue, 2));
        emp_dob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_dobActionPerformed(evt);
            }
        });
        getContentPane().add(emp_dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 140, 190, 30));

        emp_std.setEditable(false);
        emp_std.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.blue, 2));
        emp_std.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_stdActionPerformed(evt);
            }
        });
        getContentPane().add(emp_std, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 190, 190, 30));

        emp_pos.setEditable(false);
        emp_pos.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.blue, 2));
        emp_pos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_posActionPerformed(evt);
            }
        });
        getContentPane().add(emp_pos, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 240, 190, 30));

        emp_leaves.setEditable(false);
        emp_leaves.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.blue, 2));
        emp_leaves.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_leavesActionPerformed(evt);
            }
        });
        getContentPane().add(emp_leaves, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 580, 200, 30));

        emp_dedu.setEditable(false);
        emp_dedu.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.blue, 2));
        emp_dedu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_deduActionPerformed(evt);
            }
        });
        getContentPane().add(emp_dedu, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 530, 200, 30));

        emp_id.setEditable(false);
        emp_id.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.blue, 2));
        emp_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_idActionPerformed(evt);
            }
        });
        getContentPane().add(emp_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, 190, 30));

        emp_epf.setEditable(false);
        emp_epf.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.blue, 2));
        emp_epf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_epfActionPerformed(evt);
            }
        });
        getContentPane().add(emp_epf, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 480, 200, 30));

        emp_etf.setEditable(false);
        emp_etf.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.blue, 2));
        emp_etf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_etfActionPerformed(evt);
            }
        });
        getContentPane().add(emp_etf, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 530, 200, 30));

        emp_sal.setEditable(false);
        emp_sal.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.blue, 2));
        emp_sal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_salActionPerformed(evt);
            }
        });
        getContentPane().add(emp_sal, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 650, 200, 30));

        emp_fname.setEditable(false);
        emp_fname.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.blue, 2));
        emp_fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_fnameActionPerformed(evt);
            }
        });
        getContentPane().add(emp_fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 140, 190, 30));

        jLabel25.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel25.setForeground(java.awt.Color.white);
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel25.setText("Last Month Salary Details");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 450, 280, -1));

        jLabel19.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel19.setForeground(java.awt.Color.white);
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel19.setText("Email");
        jLabel19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 300, 130, -1));

        emp_gender.setEditable(false);
        emp_gender.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.blue, 2));
        emp_gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_genderActionPerformed(evt);
            }
        });
        getContentPane().add(emp_gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 290, 190, 30));

        emp_mail.setEditable(false);
        emp_mail.setColumns(20);
        emp_mail.setRows(5);
        jScrollPane1.setViewportView(emp_mail);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 290, 230, 70));

        jScrollPane3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(83, 43, 11)));

        emp_addr.setEditable(false);
        emp_addr.setColumns(20);
        emp_addr.setRows(5);
        emp_addr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(83, 43, 11), 2));
        jScrollPane3.setViewportView(emp_addr);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 330, 240, 80));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, 1050, 10));

        jLabel26.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel26.setForeground(java.awt.Color.white);
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel26.setText("ETF");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 540, 160, -1));

        emp_netSal.setEditable(false);
        emp_netSal.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.blue, 2));
        emp_netSal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_netSalActionPerformed(evt);
            }
        });
        getContentPane().add(emp_netSal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 580, 200, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/gray2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1390, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emp_allowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_allowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emp_allowActionPerformed

    private void emp_mnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_mnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emp_mnameActionPerformed

    private void emp_lnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_lnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emp_lnameActionPerformed

    private void emp_mobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_mobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emp_mobileActionPerformed

    private void emp_nicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_nicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emp_nicActionPerformed

    private void emp_dobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_dobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emp_dobActionPerformed

    private void emp_stdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_stdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emp_stdActionPerformed

    private void emp_posActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_posActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emp_posActionPerformed

    private void emp_leavesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_leavesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emp_leavesActionPerformed

    private void emp_deduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_deduActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emp_deduActionPerformed

    private void emp_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emp_idActionPerformed

    private void emp_epfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_epfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emp_epfActionPerformed

    private void emp_etfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_etfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emp_etfActionPerformed

    private void emp_salActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_salActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emp_salActionPerformed

    private void emp_fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emp_fnameActionPerformed

    private void emp_genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emp_genderActionPerformed

    private void emp_netSalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_netSalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emp_netSalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel UserInfo;
    private javax.swing.JTextArea emp_addr;
    private javax.swing.JTextField emp_allow;
    private javax.swing.JTextField emp_dedu;
    private javax.swing.JTextField emp_dob;
    private javax.swing.JTextField emp_epf;
    private javax.swing.JTextField emp_etf;
    private javax.swing.JTextField emp_fname;
    private javax.swing.JTextField emp_gender;
    private javax.swing.JTextField emp_id;
    private javax.swing.JTextField emp_leaves;
    private javax.swing.JTextField emp_lname;
    private javax.swing.JTextArea emp_mail;
    private javax.swing.JTextField emp_mname;
    private javax.swing.JTextField emp_mobile;
    private javax.swing.JTextField emp_netSal;
    private javax.swing.JTextField emp_nic;
    private javax.swing.JTextField emp_pos;
    private javax.swing.JTextField emp_sal;
    private javax.swing.JTextField emp_std;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel title1;
    private javax.swing.JPanel userleft;
    // End of variables declaration//GEN-END:variables

    private void initialize() {
        tempUser tempUserInst = tempUser.getTempUserInstance();
        String empID = tempUserInst.getUsername();
        empID = empID.substring(2, 6);
                  
        try {
            String query = "SELECT * from employee WHERE EmployeeID = '" + empID + "'";
            connection.Connector con1 = new Connector();
            Statement statement = con1.getStatement();
            ResultSet rs = statement.executeQuery(query);

            
            while (rs.next()) {
                emp_id.setText(String.valueOf(rs.getInt("EmployeeID")));
                emp_fname.setText(rs.getString("Firstname"));
                emp_mname.setText(rs.getString("Middlename"));
                emp_lname.setText(rs.getString("Lastname"));
                emp_mobile.setText(rs.getString("Mobile"));
                emp_addr.setText(rs.getString("Address"));
                emp_nic.setText(rs.getString("nic"));
                emp_gender.setText(rs.getString("Gender"));
                emp_dob.setText(rs.getString("DateOfBirth"));
                emp_std.setText(rs.getString("StartDate"));
                emp_pos.setText(rs.getString("Position"));
                emp_mail.setText(rs.getString("Email"));
            }
            
            query = "SELECT * FROM salary WHERE YEAR(Date) = YEAR(CURRENT_DATE) AND MONTH(Date) = MONTH(CURRENT_DATE - INTERVAL 1 MONTH) AND EmployeeID = '" + empID + "'";
            rs = statement.executeQuery(query); 
            
            while (rs.next()) {
                emp_allow.setText(String.valueOf(rs.getDouble("Allowance")));
                emp_dedu.setText(String.valueOf(rs.getDouble("Deduction")));
                emp_leaves.setText(String.valueOf(rs.getInt("Leaves")));
                emp_epf.setText(String.valueOf(rs.getDouble("Epf")));
                emp_etf.setText(String.valueOf(rs.getDouble("Etf")));
                emp_sal.setText(String.valueOf(rs.getDouble("calculatedSalary")));
                emp_netSal.setText(String.valueOf(rs.getDouble("netSalary")));
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

}
